### ISSUE TITLE
[HD][UAT] UAT feedback.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/hasiru-dala#47]
https://docs.google.com/spreadsheets/d/1ILdRAYekFpjZTL-b9Lu93Hu5JDRa3_G7/edit?usp=drive_web&ouid=115444501370582801094&dls=true

**Enumeration form (Registration) -** 
- Form element group - Occupational Id (Question - "Please Specify Other" is shown always, skip is not working for this question). 
- Form element Group - Waste sold per week,  is shown always, skip is not working for this question.

**Social Security Program -** 

** Plus since there is a provision to save these ids, any future update should happen to the same field irrespective of form. I can think of five places from where it can happen: 1) at the time of enumeration, 2) when I edit the enumeration form after saving it 3)  When I enrol a person into the SS program and I choose this scheme and successfully complete facilitation with application being approved. 4) When I decide to update details for this scheme at a later point (through an unplanned visit route 5) register an already availed scheme through the unplanned visit route** - Discuss 
- Display on the top (BeneficiaryName - SchemeName - PresentState - Summary & Recommendations) spills over and is not clearly visible. (SS is attached)
![Screenshot_20200722-171026.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/25c15005-8fc8-4aa6-85d4-d1e3d28f31bb)
- Form Start Facilitation - If I have to choose only a scheme for Update then it gives me error "Saving form without selecting any scheme not allowed".
- Form Register already availed Scheme - It does not ask about card number or picture of card. In this add two questions.
1. Enter the card number/scheme registration number. (mandatory)
2. Upload image or click a photo (non-mandatory).
- If I choose a scheme that is being presently facilitated from the "register already availed scheme" list, then it is added to the availed list again. Again it shows in the list of "register already availed schemes". There is no validation to check if it is being facilitated. And it appears multiple times.
Case: RecSchemeTest 002 (HP Udan Scholarship)
- Hide Edit for all the completed visits, Enrolment also.
- Select "Start Facilitation" form. (from a case whee already some scheme facilitation is going on). 
1. Select some scheme,
2. Click on Next. Click on Save and Proceed to documents Collection. 
3. On the Top, it will not show the name of the same scheme that you selected. It will show some random name. either already availed scheme or in process scheme.
- When I choose a recurring scheme from the "Register Already Availed Scheme", it lists only "Old Age Pension" for choosing the first facilitation date. 
Case - RecSchemeTest 002
If there is more than one reoccurring scheme at the same time. It gets overwritten and show anly one "Old age pension" in start facilitation.
- "Register already availed scheme" section should list all the eligible schemes. When a scheme from here is chosen, there should be a validation to check if there is any ongoing facilitation for this scheme, then the user should be asked to end that faciliation and return. Upon registering a scheme from here, a form similar that contains the result of "Application Approved" from the "Enquire Application Status" form should show up and the scheme should be moved to the availed list, if not already there.
- Planned visits list is empty while the summary shows that there are facilitations in pending statuses. See Screenshot.  
![Screenshot_20200722-204935.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/e7490a4a-2be9-4aba-a410-fa2d6415d3f7)
- Choosing the option "Application under Processing/Review" from the"Application Status Enquiry" form. Provides an option to choose the date for rescheduling and exits without generating a visit type. At least a visit does not appear in the planned visits list. No change even after syncing.
- The form lets you choose a date from the past as date for rescheduling. It lets you proceed to the summary screen and it eventually does not create a visit.  Instead, it  Should not let the user choose a date from the past.
(In Cancel form and Application status as "Application under processing/Review").
- Visit scheduling and Summary table status does not match. 
Cases - Govind Sharma, NRSchemeTestSubject 001.
- It does not list the reasons for cancellation. Only the choice to end or reschedule facilitation is provided.
Case - Test 2, Cancel visit - Driving License Application status enquiry.
- If I update any scheme details, it adds the scheme name again in Availed Scheme. So, now the scheme shows twice in Availed Scheme. 
Case - Aadhar Card- Govind Sharma. 
- All the schemes are not showing for case - Sandeep Singh. Only four schemes are there - 
1. Driving License
2. Birth Certificate
3. Ijjawal Jeevan Yojna
4. AddNRScheme001

**Comment by vindeolal** [comment]
Staging APK : https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-7757-2020-08-07-11-30-45.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- Form element group - Occupational Id (Question - "Please Specify Other" is shown always, skip is not working for this question).  **Not DONE**
- Form element Group - Waste sold per week,  is shown always, skip is not working for this question. - **Not DONE**

**Comment by vindeolal** [comment]
- For 1 & 2 forgot to deploy registration rules on staging. Deployed now.
- Fixed the display on save button use this staging app,
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-9dbd-2020-08-10-10-46-28.apk
- In case of asd asd, he doesn't have Aadhar card(required by other schemes) and any local address proof(for birth certificate), therefore he's not able to see any schemes. And Aadhar card facilitation is in progress.

**Comment by garimadosar5** [comment]
QA Notes - 2

- Not fixed.
![Screen Shot 2020-08-10 at 12.30.58 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9ae21eae-ffb3-48d5-8075-9c9f2c764ac2)

**Comment by vindeolal** [comment]
Staging APK :https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-9dbd-2020-08-10-12-43-54.apk
